/**
 * Copyright (C) 2020, ControlThings Oy Ab
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @license Apache-2.0
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mist_MistApiBridgeJni */

#ifndef _Included_mist_MistApiBridgeJni
#define _Included_mist_MistApiBridgeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mist_MistApiBridgeJni
 * Method:    register
 * Signature: (Lmist/MistApiBridge;)V
 */
JNIEXPORT void JNICALL Java_mist_MistApiBridgeJni_register
  (JNIEnv *, jobject, jobject);

/*
 * Class:     mist_MistApiBridgeJni
 * Method:    connected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_mist_MistApiBridgeJni_connected
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
