/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mist_RequestInterface */

#ifndef _Included_mist_RequestInterface
#define _Included_mist_RequestInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mist_RequestInterface
 * Method:    jniWishApiRequest
 * Signature: (Ljava/lang/String;[BLmist/sandbox/Callback;)I
 */
JNIEXPORT jint JNICALL Java_mist_RequestInterface_jniWishApiRequest
  (JNIEnv *, jobject, jstring, jbyteArray, jobject);

/*
 * Class:     mist_RequestInterface
 * Method:    jniMistApiRequest
 * Signature: (Ljava/lang/String;[BLmist/sandbox/Callback;)I
 */
JNIEXPORT jint JNICALL Java_mist_RequestInterface_jniMistApiRequest
  (JNIEnv *, jobject, jstring, jbyteArray, jobject);

/*
 * Class:     mist_RequestInterface
 * Method:    jniMistApiRequestCancel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mist_RequestInterface_jniMistApiRequestCancel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
